# Generated by Django 3.1 on 2020-12-07 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_auto_20201120_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='postcode',
            field=models.CharField(default=1234, max_length=20),
            preserve_default=False,
        ),
    ]
