# Generated by Django 3.1 on 2020-12-17 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_coupon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
