# Generated by Django 3.1 on 2020-10-23 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20201023_1215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'friendly_name', 'verbose_name_plural': 'Categories'},
        ),
    ]
